23:E5:D1:37:31:31:60:4D:
  set_brightness_max:
  get_brightness_max: 100
  before_set_brightness_turn_on: false
  config_offline_is_off: false
9A:E4:CC:32:34:39:4F:0A:
  set_brightness_max:
  get_brightness_max: 100
  before_set_brightness_turn_on: false
  config_offline_is_off: false
67:CA:C7:6A:04:86:55:3A:
  set_brightness_max:
  get_brightness_max: 100
  before_set_brightness_turn_on: false
  config_offline_is_off: false
FA:C3:CD:37:31:31:15:51:
  set_brightness_max:
  get_brightness_max: 100
  before_set_brightness_turn_on: false
  config_offline_is_off: false
